### PR TITLE
Update buildspec.yml

### PR DESCRIPTION
**Pull request by umar-siddiqui-ivolve**
please fix

### CODE REVIEW

**Comment by awsfanboy** [comment]
you can create a issue here https://github.com/DevOpsLK/eks-codepipeline-cicd/issues @umar-siddiqui-ivolve

**Comment by awsfanboy** [comment]
@umar-siddiqui-ivolve  could you please create an issue with your error ?

**Comment by umar-siddiqui-ivolve** [comment]
I have created the issue. please fix asap


Regards,


[cid:49a44445-008c-4dd7-938e-b2fd9cf22c47]

Muhammad Umar Siddiqui
Sr. DevOps Engineer

Mobile: +92307-2757483
+92 21 111 iVolve (486-583)<tel:+92%2021%20111%20486-583> | ***@***.***

www.ivolve.io<http://www.ivolve.io/>

NGC Tower, 3rd Floor, Plot #A-1, Block-3 7/8 KECHS,
Jinnah Housing Society, PECHS, Karachi, 75000, Pakistan

________________________________

**Comment by umar-siddiqui-ivolve** [comment]
hello any update?


Regards,


[cid:6a6eb584-f521-4606-8c85-86b495608e0d]

Muhammad Umar Siddiqui
Sr. DevOps Engineer

Mobile: +92307-2757483
+92 21 111 iVolve (486-583)<tel:+92%2021%20111%20486-583> | ***@***.***

www.ivolve.io<http://www.ivolve.io/>

NGC Tower, 3rd Floor, Plot #A-1, Block-3 7/8 KECHS,
Jinnah Housing Society, PECHS, Karachi, 75000, Pakistan

________________________________

**Comment by damithkothalawala** [comment]
උඹට පිස්සුද බං pull requests වලට comment දදා ඉන්න ? ඕක ලියපු එකා ඉන්නේ නවසීලන්⁣තයේ. 

මුලින්ම හරි විදියට වැඩ කරන්න ඉගෙන ගනින් පට්ටි හරකා (නවසීලන්තයේ සයිස් එකා)

**Comment by awsfanboy** [comment]
`[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ REPOSITORY=11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ TAG=v1.2
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ echo $REPOSITORY
11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ echo $TAG
v1.2
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY:$TAG"'@' Kubernetes/eks-deployment.yml
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ cat Kubernetes/eks-deployment.yml `
---
`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-demo
  name: deployment-eks-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-eks-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-eks-demo
    spec:
      containers:
      - image: 11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo:v1.2
        imagePullPolicy: Always
        name: app-eks-demo
        ports:
        - containerPort: 80`

hi @umar-siddiqui-ivolve  this is a very basic sed command and i have tested already as above. no errors and it replaced the "CONTAINER_IMAGE". you have not provided sufficient information including the exact error. hence i am closing this issue as a false issue.

**Pull request closed without merging**
